### ISSUE TITLE
Additional values

### ISSUE THREAD

**Issue by toessfrosch** [Fabian-Schmidt/esphome-victron_ble#39]
Would it be possible to add more values such as "panel_voltage" or "yield_total"?
and if so, how can this be implemented?

**Comment by Fabian-Schmidt** [comment]
Hi,
I am assuming this is for a Solar charger like SmartSolar MPPT.
I receive the following values:
- PV_POWER in W
- YIELD_TODAY in kWh

I cannot add additional fields. They are defined by Victron.

**Comment by RetoLu** [comment]
I understand, but they seem to be present on the TTL communication interface. See https://github.com/KinDR007/VictronMPPT-ESPHOME and also in the Mobile APP.
Previously I had used this solution but now my Victron TTL interface no longer works so I have switched to the bluetooth version.

**Comment by Fabian-Schmidt** [comment]
Correct.
This component is using the Instant readout (Bluetooth advertising) feature. So only the information which you can see in the Victron app on the overview page are transmitted by the device. The upside is you can receive this data my multiple devices as there is no active connection between the Victron device and the ESP32.
So I don't request any data and have no active communication with the Victron device. Because the Victron device just broadcast the information via Bluetooth.

If you need the additional information you must use the other component which uses the ve.direct protocol for communication.
Victron has not documented the Bluetooth communication used by the App to read additional information.
