### ISSUE TITLE
Thank you and inverter-related questions

### ISSUE THREAD

**Issue by bazsodombiandras** [Fabian-Schmidt/esphome-victron_ble#82]
I've opened this issue before anything else to thank you for this very nice Victron Energy integration with ESPHome. I appreciate the work you put into this. I've discovered it only some days/weeks ago and started using it recently.

I've noticed that the information published for VE BlueSolar charge controllers (which I'm using this integration for) is quite poor, for example the voltage and current from solar panels is not available. I recall reading on some forum that this is Victron's fault in the sense that they don't publish this data over Bluetooth, so it's not a problem with this integration, but with the Victron software that runs on the charge controller itself.

My question is: have you tried talking to them, convincing them to publish more data? I would like to contact them myself too and ask for better support for the BlueSolar charge controllers over Bluetooth. Do you know what channel of communication would be best to ask for this support?

Thank you for everything and keep up the good work. I'm sure many people find it very useful.

**Comment by Fabian-Schmidt** [comment]
It is correct that I publish all available data which are transmitted in the Bluetooth announcement packages submitted by the Victron device.

There are technical limits how many bytes can be submitted via Bluetooth announcement packages. Usually between 20 and 30 bytes (160 - 240 bits). For example the Solar Charger messages uses 121 of 160 bits. So only 39 bits are free. Two numbers usually occupy 32 bits.

Could Victron extend the messages? Yes. But they cannot submit all data as Bluetooth announcement due to above technical limit. I personally find the fields they chosen good and I had no need for additional fields as they are meaningless and just for the internal operations of the device. For example for a solar charger the voltage and amps of the solar cell is not important only the resulting power is important and this value is included.

Have I contacted Victron and ask them? No. I had zero contact with Victron. So no idea who to ask and how to justify the change.

If you manage to convince Victron to include additional data in Bluetooth announcement packages I am happy to integrate them in the component.

Cheers

**Comment by bazsodombiandras** [comment]
Thank you for your reply.
Wow, that 160 bits limit is really tight :( I suppose they could publish more data via alternating multiple Bluetooth announcement messages identified by some header id or something.

**Comment by bazsodombiandras** [comment]
Thank you for the clarifications.
