### ISSUE TITLE
feature request write via BLE or ve.direct possible ?

### ISSUE THREAD

**Issue by kjk25** [Fabian-Schmidt/esphome-victron_ble#85]
Hi ,

i like to change the charge current for a Victron smart-solar 100|50 . 
to limitate the current.

i can allready read thrue the uart port, and set the current via the BLE APP of corse.

hope it will work,
KK

**Comment by Fabian-Schmidt** [comment]
Hi,

It cannot be set using this component. This component is read only and has no 'active' communication to the device. It just listens to the Bluetooth announcement packages broadcasted.

It should be possible to set this value via the ve.direct. I don't know the ve.direct components. Based on the documented they must use the HEX protocol instead of the text protocol to update any values. Unsure which component does it.
